services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PHP_CS_FIXER_IGNORE_ENV: 1
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null
