framework:
    cache:
        prefix_seed: 'stochastix.download'

    messenger:
        transports:
            stochastix: '%env(MESSENGER_TRANSPORT_DSN)%'

        buses:
            messenger.bus.default:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - doctrine_open_transaction_logger
                    - doctrine_transaction

        routing:
            'Stochastix\Domain\Backtesting\Message\RunBacktestMessage': stochastix
            'Stochastix\Domain\Data\Message\DownloadDataMessage': stochastix

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true

doctrine:
    orm:
        mappings:
            StochastixBundle:
                is_bundle: true
                type: attribute
                dir: 'src/'
                prefix: 'Stochastix\'
                alias: StochastixBundle

