services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Stochastix\:
        resource: '../src/*'
        exclude:
            - '../src/Common'
            - '../src/DependencyInjection'
            - '../src/Indicator'
            - '../src/Order'
            - '../src/**/Dto'
            - '../src/**/Enum'
            - '../src/**/Exception'
            - '../src/**/Event'
            - '../src/**/Model'

    stochastix.download.cancel.cache:
        class: Symfony\Component\Cache\Adapter\FilesystemAdapter
        arguments:
            - 'stochastix.download.cancel'
            - 3600
            - '%kernel.project_dir%/data/.cache'
        tags:
            - { name: 'cache.pool', namespace: 'stochastix.download' }
